baseURL = "http://rocdev.org"
languageCode = "en-us"
title = "RocDev"

[params]
    author = "RocDev"
    description = "Promoting Software Development in the Greater Rochester Area"
    githubUsername = "#585-software"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = false
    highlightStyle = "solarized-dark"
    highlightLanguages = ["javascript"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/code-of-conduct/"
    name = "Code of Conduct"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "https://five-eight-five-slack.herokuapp.com/"
    name = "slack"
    weight = 1

[[menu.icon]]
    url = "https://www.meetup.com/meetup-group-BkuJclOW/"
    name = "meetup"
    weight = 2

[[menu.icon]]
    url = "https://github.com/585-software/"
    name = "github"
    weight = 3
